'use strict';
const BUILD='20261004-6';
const E=SigmaEngine,$=id=>document.getElementById(id);
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const examples=['sum(binomial(n,k)^2,k,0,n)','sum(stirling2(n,k),k,0,n)','prod(k,k,1,n)','sum(binomial(n,k)^2*binomial(n+k,k)^2,k,0,n)'];
let result=null,worker=null,job=0,toastTimer;
function math(a){
 const fence=x=>'<mrow><mo>(</mo>'+x+'<mo>)</mo></mrow>';
 const priority=x=>x.type==='bin'?({'+':1,'-':1,'*':2,'/':2,'^':4}[x.op]):x.type==='neg'?3:5;
 function draw(x){
  if(x.type==='num'){let negative=x.value.a<0n,n=negative?-x.value.a:x.value.a;let value=x.value.b===1n?'<mn>'+n+'</mn>':'<mfrac><mn>'+n+'</mn><mn>'+x.value.b+'</mn></mfrac>';return negative?'<mrow><mo>−</mo>'+value+'</mrow>':value;}
  if(x.type==='var')return '<mi>'+escapeHTML(x.name)+'</mi>';
  if(x.type==='neg')return '<mrow><mo>−</mo>'+(priority(x.x)<3?fence(draw(x.x)):draw(x.x))+'</mrow>';
  if(x.type==='bin'){
   let left=draw(x.left),right=draw(x.right),p=priority(x);
   if(x.op==='/')return '<mfrac>'+left+right+'</mfrac>';
   if(x.op==='^'){if(priority(x.left)<=4||(x.left.type==='num'&&x.left.value.a<0n))left=fence(left);return '<msup>'+left+right+'</msup>';}
   if(priority(x.left)<p)left=fence(left);
   if(priority(x.right)<p||(x.op==='-'&&priority(x.right)===p))right=fence(right);
   let op=x.op==='*'?(x.left.type==='num'&&x.right.type!=='num'?'⁢':'·'):x.op==='-'?'−':x.op;
   return '<mrow>'+left+'<mo>'+op+'</mo>'+right+'</mrow>';
  }
  let [body,k,lo,hi]=x.args;
  if(x.name==='sum'||x.name==='prod')return '<mrow><munderover><mo movablelimits="false">'+(x.name==='sum'?'∑':'∏')+'</mo><mrow>'+draw(k)+'<mo>=</mo>'+draw(lo)+'</mrow>'+draw(hi)+'</munderover>'+(priority(body)<=1?fence(draw(body)):draw(body))+'</mrow>';
  if(x.name==='binomial')return fence('<mfrac linethickness="0">'+draw(body)+draw(k)+'</mfrac>');
  if(x.name==='factorial')return '<mrow>'+(priority(body)<5?fence(draw(body)):draw(body))+'<mo>!</mo></mrow>';
  const names={bell:'B',catalan:'C',fibonacci:'F',lucas:'L',bernoulli:'B',harmonic:'H',stirling2:'S',stirling1:'c',stirling1s:'s'};
  return '<mrow><mi mathvariant="normal">'+escapeHTML(names[x.name]||x.name)+'</mi><mo>⁡</mo>'+fence('<mrow>'+x.args.map(draw).join('<mo>,</mo>')+'</mrow>')+'</mrow>';
 }
 return '<math xmlns="http://www.w3.org/1998/Math/MathML" display="block" aria-label="'+escapeHTML(E.format(a))+'">'+draw(a)+'</math>';
}
function preview(){try{let a=E.parse($('expression').value,['n',...($('input-mode').value==='queries'?['m']:[]),...Object.keys(SigmaQueries.parameters($('parameters').value))]);$('math-preview').innerHTML=math(a);$('parse-status').textContent='入力を確認済み';}catch(e){$('math-preview').textContent=$('expression').value||'ここに数式が表示されます';$('parse-status').textContent=e.message}if(result)$('stale').hidden=false}
function view(name){document.querySelectorAll('.view').forEach(x=>x.hidden=x.id!==name);$('query-results').hidden=name!=='calculator'||!result||result.mode!=='queries';document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$('breadcrumb').textContent={calculator:'数式の計算',dictionary:'関数の説明',guide:'入力形式と計算方法',algorithms:'計算法・対応状況'}[name];window.scrollTo({top:0,behavior:'smooth'})}
function tab(name){document.querySelectorAll('.tab-panel').forEach(x=>x.hidden=x.id!==name);document.querySelectorAll('.tabs button').forEach(x=>{let on=x.dataset.tab===name;x.classList.toggle('active',on);x.setAttribute('aria-selected',String(on))})}
function insert(text){if($('calculator').hidden)view('calculator');let el=$('expression'),start=el.selectionStart,end=el.selectionEnd,selected=el.value.slice(start,end),marker=text.indexOf('□');if(marker>=0){text=text.replace('□',selected||'n')}el.setRangeText(text,start,end,'end');el.focus();if(marker>=0)el.setSelectionRange(start+marker,start+marker+(selected||'n').length);preview()}
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,2600)}
function revive(x){if(Array.isArray(x))return x.map(revive);if(x&&typeof x==='object'){if(typeof x.a==='bigint'&&typeof x.b==='bigint')return new E.Q(x.a,x.b);for(let k of Object.keys(x))x[k]=revive(x[k])}return x}
async function run(){let id=++job,source=$('expression').value,options={mode:$('input-mode').value,parameters:$('parameters').value,queries:$('query-points').value,array:$('query-array').value,start:Number($('start').value),count:Number($('count').value),maxOrder:Number($('max-order').value),maxDegree:Number($('max-degree').value)},time=performance.now();if(worker)worker.terminate();$('error').hidden=true;$('busy').hidden=false;$('calculate').disabled=true;
 try{let data;if(location.protocol==='file:'){await new Promise(r=>setTimeout(r,20));data=SigmaQueries.run(source,options)}else data=await new Promise((resolve,reject)=>{const activeWorker=new Worker('worker.js?v='+BUILD);worker=activeWorker;let timer=setTimeout(()=>{activeWorker.terminate();reject(Error('解析が20秒を超えました。項数または式を小さくしてください'))},20000);activeWorker.onmessage=event=>{clearTimeout(timer);activeWorker.terminate();event.data.error?reject(Error(event.data.error)):event.data.build!==BUILD?reject(Error('計算用ファイルの版が一致しません。公開用10ファイルを同じ最新版に更新し、Ctrl＋F5で再読み込みしてください。')):resolve(revive(event.data.result))};activeWorker.onerror=()=>{clearTimeout(timer);activeWorker.terminate();reject(Error('計算用ファイルを読み込めませんでした。worker.js・engine.js・optimize.jsが同じフォルダーにあるか確認し、公開用ファイルを一式更新してください'))};activeWorker.postMessage({source,options})});if(id!==job)return;if(!data||(data.mode!=='queries'&&(!data.simple||!data.structure||!data.search)))throw Error('解析結果に必要な情報がありません。計算用ファイルを一式更新してください。');result=data;render();$('stale').hidden=source===$('expression').value&&options.start===Number($('start').value)&&options.count===Number($('count').value)&&options.maxOrder===Number($('max-order').value)&&options.maxDegree===Number($('max-degree').value);$('query-timing').textContent=Math.round(performance.now()-time)+' ms';$('timing').textContent=options.count+' terms · '+Math.round(performance.now()-time)+' ms';try{localStorage.setItem('sigma-lab-input',source);localStorage.setItem('sigma-lab-state',JSON.stringify({source,mode:options.mode,parameters:options.parameters,queries:options.queries,array:options.array}))}catch{}}
 catch(e){if(id!==job)return;console.error(e);$('error').textContent=e.message;$('error').hidden=false;$('results').hidden=true;$('query-results').hidden=true;if(result)$('stale').hidden=false}finally{if(id===job){$('busy').hidden=true;$('calculate').disabled=false}}
}
function render(){if(result.mode==='queries'){renderQueries();return;}$('query-results').hidden=true;let {simple,steps,seq,g,gf,start,count}=result;$('results').hidden=false;$('terms-badge').textContent=count;$('simplified').innerHTML=math(simple);$('identity-badge').textContent=steps.length?'恒等式で変形':'入力の定義';$('identity-note').textContent=steps.length?'n ≥ 0 の整数で成り立つ、登録済みの変形規則を適用しました。':'登録済みの簡約規則では、これ以上変形できませんでした。';$('steps').hidden=!steps.length;$('step-list').innerHTML=steps.map(s=>'<li>'+escapeHTML(s)+'</li>').join('');
 $('gf-formula').textContent=gf?gf.formula:'—';$('gf-badge').textContent=gf?(gf.proven?'既知の '+(gf.kind.includes('指数')?'EGF':'OGF'):'推測・未証明'):'未検出';$('gf-note').textContent=gf?(gf.kind+' · '+(gf.proven?'定義・既知の公式から取得。':gf.algebraic?'G(x)=Σ a(n)xⁿ。最後の8係数で独立検算。枝は初期係数で選択。':'定数係数の漸化式候補から構成。')):(start!==0?'母関数を調べるには開始 n を 0 にしてください。':'登録公式・有理型候補では検出できませんでした。存在しないことを意味しません。');
 $('recurrence').textContent=g?E.recurrenceText(g):'探索範囲内に、検算を通過する候補はありません。';$('rec-badge').textContent=g?(g.proven?'記号的検証済み':'推測・未証明'):'未検出';$('rec-note').textContent=g?'階数 '+g.order+' · 係数の次数 '+g.degree+' · '+g.train+' 項から推測 / 未使用の '+g.holdout+' 項で一致。'+(g.proven?g.certificate:'有限個の一致は証明ではありません。'):'階数 ≤ '+result.search.maxOrder+'、次数 ≤ '+result.search.maxDegree+'、未知係数 ≤ 36 の範囲を探索。ベル数など、この形式で表せない数列もあります。';
 $('sequence-label').textContent='n = '+start+' … '+(start+7);$('sequence').innerHTML=seq.slice(0,8).map((x,i)=>'<div><small>n = '+(start+i)+'</small><b title="'+x+'">'+x+'</b></div>').join('');$('value-rows').innerHTML=seq.map((x,i)=>'<tr class="'+(g&&i>=g.train?'holdout':'')+'"><td>'+(start+i)+'</td><td>'+x+'</td><td>'+(g?(i<g.train?'係数の推定':'独立検算 ✓'):'厳密評価')+'</td></tr>').join('');document.querySelector('#code-mode option[value="recurrence"]').disabled=!g;if(!g&&$('code-mode').value==='recurrence')$('code-mode').value='fast-nth';$('structure-note').textContent=result.structure.type+'：'+result.structure.reason;$('algorithm-note').textContent=result.fast?result.fast.method+' ／ '+(result.fast.proven?'恒等式・記号的検証に基づく':'推測に基づく・未証明'):'対応する高速計算法は未検出です。項数・探索上限の変更や厳密値モードを利用してください。';$('complexity-note').textContent=result.fast?'第N項: '+result.fast.nthComplexity+' ／ 列: '+result.fast.prefixComplexity+'。M(t)=O(t log t)。':'';renderCode();}
function generatedCode(){let mode=$('code-mode').value;return mode.startsWith('fast-')?SigmaFastCPP.generate(result,mode==='fast-nth'?'nth':'prefix'):SigmaCPP.generate(result,mode)}
function renderCode(){if(!result)return;let mode=$('code-mode').value,fast=mode.startsWith('fast-');$('arithmetic-note').textContent=fast?'C++17 / mod 998244353 / 外部ライブラリ不要':'C++17 / Boost / 厳密有理数';try{$('cpp-code').textContent=generatedCode();$('download-code').disabled=false;$('copy-code').disabled=false;$('code-note').textContent=fast?(result.fast.method+'。'+(mode==='fast-nth'?'coefficient(N) は a(N) を返します。':'coefficients(N) は START='+(result.fast.start||0)+' から N までの列を返します。')+(result.fast.proven?' 恒等式・記号的検証に基づきます。':' 未証明の推測を使用します。')+' 計算量・定義域はコードのコメントと使い方を参照してください。'):mode==='recurrence'?'初期値と専用漸化式だけを出力します。未解決の特異点では例外になります。':'定義から厳密評価する汎用版です。高速化には上の高速モードを選んでください。'}catch(e){$('cpp-code').textContent='// '+e.message;$('code-note').textContent=e.message;$('download-code').disabled=true;$('copy-code').disabled=true}}
function download(text,name,type){let url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000)}
function dictionary(){let query=$('function-search').value.toLowerCase().trim(),category=$('category').value,list=E.CATALOG.filter(f=>(category==='すべて'||category===f.category)&&[f.id,f.name,f.description].join(' ').toLowerCase().includes(query));$('dictionary-info').textContent=list.length+' / '+E.CATALOG.length+' 関数 · クリックしてカーソル位置に挿入';$('function-list').innerHTML=list.map(f=>'<article class="card function-card"><span class="function-category">'+f.category+'</span><h3>'+f.name+'</h3><code>'+f.example+'</code><p>'+f.description+'</p><div class="definition">'+escapeHTML(f.formula)+'</div><button class="secondary" data-insert="'+f.example+'">数式に挿入 ＋</button></article>').join('')||'<p>該当する関数がありません。</p>'}

function functionButtons(){
 const labels={stirling1:'スターリング数・第一種',stirling1s:'スターリング数・第一種（符号付）',stirling2:'スターリング数・第二種',eulerian:'オイラー数（Eulerian）',euler:'オイラー数（Euler）',lah:'ラー数',totient:'トーシェント',mobius:'メビウス関数'};
 const groups=[...new Set(E.CATALOG.map(f=>f.category))];
 $('function-buttons').innerHTML=groups.map(category=>'<div class="function-group"><h4>'+category+'</h4><div>'+E.CATALOG.filter(f=>f.category===category).map(f=>'<button type="button" class="function-insert" data-function="'+f.id+'" data-insert="'+f.example.replace('(n','(□')+'" title="'+escapeHTML(f.example+' — '+f.description)+'" aria-describedby="function-help">'+escapeHTML(labels[f.id]||f.name)+'</button>').join('')+'</div></div>').join('');
 function explain(event){let button=event.target.closest('[data-function]');if(!button)return;let f=E.CATALOG.find(f=>f.id===button.dataset.function);$('function-help').innerHTML='<strong>'+escapeHTML(f.name)+'</strong> <code>'+escapeHTML(f.example)+'</code><span>'+escapeHTML(f.description)+' '+escapeHTML(f.formula)+'</span>'}
 $('function-buttons').addEventListener('pointerover',explain);$('function-buttons').addEventListener('focusin',explain);
}
document.addEventListener('click',event=>{let el=event.target.closest('button');if(!el)return;if(el.dataset.view)view(el.dataset.view);if(el.dataset.tab)tab(el.dataset.tab);if(el.dataset.insert)insert(el.dataset.insert);if(el.dataset.example!==undefined){$('input-mode').value='sequence';modeChanged();$('expression').value=examples[Number(el.dataset.example)];$('start').value=0;preview();view('calculator');tab('overview');run()}});
$('expression').addEventListener('input',()=>{if($('input-mode').value==='queries')invalidate();preview()});$('expression').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();run()}});$('calculate').addEventListener('click',run);$('code-mode').addEventListener('change',renderCode);$('function-search').addEventListener('input',dictionary);$('category').addEventListener('change',dictionary);['start','count','max-order','max-degree'].forEach(id=>$(id).addEventListener('change',()=>{if(result)$('stale').hidden=false}));
$('download-code').addEventListener('click',()=>{if(result)download(generatedCode(),'sigma.cpp','text/x-c++src')});$('download-csv').addEventListener('click',()=>{if(result)download('n,a(n)\r\n'+result.seq.map((x,i)=>(result.start+i)+','+x).join('\r\n'),'sigma-values.csv','text/csv;charset=utf-8')});$('copy-code').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('cpp-code').textContent);toast('C++ コードをコピーしました')}catch{toast('コピーできませんでした。.cpp を保存してください')}});
const queryExamples=[['二項部分和 / Mo','sum(binomial(n,k),k,0,m)'],['スターリング / DP・NTT','stirling2(n,m)'],['二変数多項式','sum(2*k*k+3*m*k,k,0,n)'],['矩形和','sum(sum(gcd(i,j),j,0,m),i,0,n)'],['floor_sum','sum(floor((3*k+2)/m),k,0,n-1)'],['互いに素な組数','sum(mobius(k)*floor(n/k)*floor(m/k),k,1,min(n,m))'],['配列の区間和','sum(array(k),k,n,m)'],['配列のdistinct','distinct(n,m)'],['配列の最小値','range_min(n,m)']];
function invalidate(){result=null;job++;if(worker)worker.terminate();$('busy').hidden=true;$('calculate').disabled=false;$('results').hidden=true;$('query-results').hidden=true;}
function modeChanged(){invalidate();const query=$('input-mode').value==='queries';$('query-inputs').hidden=!query;$('sequence-search').hidden=query;$('sequence-settings').hidden=query;if(result){$('results').hidden=true;$('query-results').hidden=true;}preview();}
function renderQueries(){ $('results').hidden=true;$('query-results').hidden=false;$('query-formula').innerHTML=math(result.ast);$('query-algorithm').innerHTML=result.choices.map(p=>'<option value="'+p.id+'">'+escapeHTML(p.name)+'</option>').join('')||'<option value="">対応手法は未検出</option>';$('query-values').innerHTML=result.values.map(x=>'<tr><td>'+x.n+'</td><td>'+x.m+'</td><td>'+escapeHTML(x.error||x.value)+'</td><td>'+(x.value!==null?String(SigmaOptimize.residue(x.value)):'—')+'</td></tr>').join('');renderQueryCode();}
function renderQueryCode(){if(!result||result.mode!=='queries')return;let p=result.choices.find(x=>x.id===$('query-algorithm').value);$('query-cost').textContent=p?p.cost:'式の形に適用できる実装済みの高速化がありません。計算法・対応状況を確認してください。';$('query-condition').textContent=p?p.condition:'';try{$('query-code').textContent=SigmaQueryCPP.generate(result,p&&p.id,$('query-output').value);$('query-code-note').textContent='C++17 / GCC・Clang / mod 998244353 / 外部ライブラリ不要。入力: '+($('query-output').value==='grid'?'N M（0..N × 0..Mの全表）':p.array?'L、L個の配列値、Q、Q組の n m':'Q、Q組の n m')+'。solve_queries()は入力順の答えを返します。U=max n、V=max m、D=異なるnの個数、L=配列長です。';$('query-copy').disabled=false;$('query-download').disabled=false;}catch(e){$('query-code').textContent='// '+e.message;$('query-code-note').textContent=e.message;$('query-copy').disabled=true;$('query-download').disabled=true;}}
$('query-algorithm').addEventListener('change',renderQueryCode);$('query-output').addEventListener('change',renderQueryCode);
$('input-mode').addEventListener('change',modeChanged);
$('parameters').addEventListener('input',()=>{invalidate();preview();if(result){$('results').hidden=true;$('query-results').hidden=true;}});
for(const id of ['query-points','query-array'])$(id).addEventListener('input',invalidate);
$('query-download').addEventListener('click',()=>download($('query-code').textContent,'sigma-queries.cpp','text/x-c++src'));
$('query-copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('query-code').textContent);toast('C++コードをコピーしました')}catch{toast('.cppを保存してください')}});
$('query-csv').addEventListener('click',()=>{if(result&&result.mode==='queries')download('n,m,value\r\n'+result.values.map(x=>[x.n,x.m,x.value===null?'':x.value].join(',')).join('\r\n'),'sigma-queries.csv','text/csv;charset=utf-8')});
$('query-examples').innerHTML=queryExamples.map(([label],i)=>'<button class="secondary" data-query-example="'+i+'">'+label+'</button>').join('');
$('query-examples').addEventListener('click',event=>{const button=event.target.closest('[data-query-example]');if(!button)return;const i=Number(button.dataset.queryExample);$('expression').value=queryExamples[i][1];$('parameters').value='';$('query-points').value=i>=6?'0 0\n0 3\n2 7\n4 9':i===4?'0 1\n3 2\n5 3\n8 5':'0 0\n3 2\n5 3\n8 5';preview();run();});
$('algorithm-catalog').innerHTML=SigmaQueries.catalog.map(([name,status,description])=>'<article class="card catalog-item"><div><h3>'+escapeHTML(name)+'</h3><span class="badge '+(status==='実装済み'?'green':'')+'">'+status+'</span></div><p>'+escapeHTML(description)+'</p></article>').join('');
$('function-count').textContent=E.CATALOG.length;$('palette-count').textContent=E.CATALOG.length+'種類';try{let previous=localStorage.getItem('sigma-lab-input');if(previous)$('expression').value=previous;let state=JSON.parse(localStorage.getItem('sigma-lab-state')||'null');if(state&&typeof state.source==='string'){$('expression').value=state.source;$('input-mode').value=state.mode==='queries'?'queries':'sequence';$('parameters').value=state.parameters||'';$('query-points').value=state.queries||$('query-points').value;$('query-array').value=state.array||'';$('query-inputs').hidden=$('input-mode').value!=='queries';$('sequence-search').hidden=$('input-mode').value==='queries';$('sequence-settings').hidden=$('input-mode').value==='queries';}}catch{}functionButtons();dictionary();preview();run();
