(function(root){
'use strict';
const E=root.SigmaEngine||(typeof require!=='undefined'?require('./engine.js'):null),O=root.SigmaOptimize||(typeof require!=='undefined'?require('./optimize.js'):null),F=root.SigmaFastCPP||(typeof require!=='undefined'?require('./fast-cpp.js'):null);
const lit=x=>String(O.residue(x));
function generate(result,id,target='queries'){const p=result.choices.find(x=>x.id===(id||result.choices[0]?.id));if(!p)throw Error('この式に対するクエリ高速化は未検出です。対応例・適用条件を確認してください。');let defs='',body='',seqSerial=0;
 const names=result.variables||['n','m'],legacy=names.length===2&&names.includes('n')&&names.includes('m'),fields=names.map((x,i)=>legacy?x:'coordinate_'+i),mapping=Object.fromEntries(names.map((x,i)=>[x,fields[i]]));let aliases={...mapping};const field=x=>{if(!aliases[x])throw Error('未束縛の変数: '+x);return aliases[x]},bindings=fields.map(f=>'auto '+f+'=q.'+f+';').join('');
 function embed(ast,choice,variables){let code=generate({source:E.format(ast),ast,choices:[choice],variables,params:result.params},choice.id).split('#ifndef SIGMA_NO_MAIN')[0].replace(/^#include .*$/gm,'');let name='subquery_'+seqSerial++;defs+='\nnamespace '+name+' {\n'+code+'\n}\n';return {name,fields:variables.length===2&&variables[0]==='n'&&variables[1]==='m'?variables:variables.map((_,i)=>'coordinate_'+i)};}

 const useNTT=p.id==='stirling-fps',library=F.library(useNTT?['ntt','factorials']:['mod']);
 function seq(plan){const name='sequence_'+seqSerial++;const code=F.generate({source:'required sequence',fast:{...plan,start:0,method:'Sequence precomputation',nthComplexity:'see caller',prefixComplexity:'see caller'}},'prefix').split('#ifndef SIGMA_NO_MAIN')[0].replace(/^#include .*$/gm,'');defs+='\nnamespace '+name+' {\n'+code+'\n}\n';return N=>'[&](){auto tmp='+name+'::coefficients('+N+'); Poly out;out.reserve(tmp.size());for(auto x:tmp)out.push_back(mint(x.v));return out;}()';}
 function integer(a){if(a.type==='num'&&a.value.b===1n){if(a.value.a < -1000000000000n||a.value.a>1000000000000n)throw Error('整数引数の定数は絶対値10^12以下です');return '(__int128('+a.value.a+'))';}if(a.type==='var')return '(__int128('+field(a.name)+'))';if(a.type==='neg')return '(-'+integer(a.x)+')';if(a.type==='bin'&&['+','-','*'].includes(a.op))return '(__int128(checked_signed('+integer(a.left)+a.op+integer(a.right)+')))';throw Error('整数の添字に変換できません: '+E.format(a));}
 function expr(a){if(a.type==='num')return 'mint('+lit(a.value)+')';if(a.type==='var')return 'mint('+field(a.name)+')';if(a.type==='neg')return '(-'+expr(a.x)+')';if(a.type==='bin'){if(a.op==='^')return '('+expr(a.left)+').pow(checked_nonnegative('+integer(a.right)+'))';return '('+expr(a.left)+a.op+expr(a.right)+')'}let args=a.args.map(integer),small=args.map(x=>'checked_signed('+x+')');switch(a.name){case 'factorial':return 'comb.factorial('+small[0]+')';case 'binomial':return 'comb.choose('+small.join(',')+')';case 'rising':return 'comb.rising('+small.join(',')+')';case 'falling':return 'comb.falling('+small.join(',')+')';case 'gcd':return 'mint(std::gcd('+small.join(',')+'))';case 'lcm':return 'lcm_mod('+small.join(',')+')';case 'min':case 'max':return 'mint(std::'+a.name+'('+small.join(',')+'))';case 'abs':return 'mint(llabs('+small[0]+'))';default:throw Error('セルの高速評価は未対応です: '+a.name)}}
 const maxcoord='long long U=0,V=0;for(auto q:qs){U=max(U,q.n);V=max(V,q.m);}';
 if(p.id==='polynomial'){const terms=p.terms.map(t=>'mint('+lit(t.coefficient)+')'+Object.entries(t.powers).map(([x,k])=>'*mint('+field(x)+').pow('+k+')').join(''));body='for(auto q:qs){'+bindings+'answer[q.id]='+ (terms.join('+')||'mint(0)')+';}';}
 if(p.id==='direct')body='Comb comb;for(auto q:qs){'+bindings+'answer[q.id]='+expr(p.expression)+';}';
 if(['prefix','product-prefix','fenwick','segment','sparse','distinct-mo','distinct-fenwick'].includes(p.id)){
  let arr;if(p.array)arr='Poly values;for(auto x:data)values.push_back(mint(x));';else{let make=seq(p.sequence);arr='long long U=0;for(auto q:qs)U=max(U,q.m);check_prefix(U);Poly values='+make('int(U)')+';';}
  if(['prefix','product-prefix'].includes(p.id)){body=arr+'int L=int(values.size());validate_ranges(qs,L);';if(p.id==='prefix')body+='Poly pref(L+1);for(int i=0;i<L;i++)pref[i+1]=pref[i]+values[i];for(auto q:qs)answer[q.id]=pref[q.m+1]-pref[q.n];';else body+='Poly pref(L+1,1),inv(L+1);vector<int> zeros(L+1);for(int i=0;i<L;i++){zeros[i+1]=zeros[i]+(values[i].v==0);pref[i+1]=pref[i]*(values[i].v?values[i]:mint(1));}inv[L]=pref[L].inv();for(int i=L-1;i>=0;i--)inv[i]=inv[i+1]*(values[i].v?values[i]:mint(1));for(auto q:qs)answer[q.id]=zeros[q.m+1]>zeros[q.n]?mint(0):pref[q.m+1]*inv[q.n];';}
  if(p.id==='fenwick'){defs+=fenwick;body='validate_ranges(qs,int(data.size()));Fenwick tree(data);for(auto q:qs)answer[q.id]=tree.prefix(q.m+1)-tree.prefix(q.n);';}
  if(p.id==='segment'){
   let identity=p.op==='product'?'1':p.op==='min'?'LLONG_MAX':p.op==='max'?'LLONG_MIN':'0',combine=p.op==='sum'?'(mint(a)+mint(b)).v':p.op==='product'?'(mint(a)*mint(b)).v':p.op==='gcd'?'std::gcd(a,b)':'std::'+p.op+'(a,b)',normalize=p.op==='gcd'?'llabs(x)':p.op==='sum'||p.op==='product'?'mint(x).v':'x';
   defs+=`struct SegmentTree {int size=1,length;vector<long long> t;static long long identity(){return ${identity};}static long long op(long long a,long long b){return ${combine};}static long long normalize(long long x){if(x < -1000000000000LL||x>1000000000000LL)throw runtime_error("array value out of range");return ${normalize};}SegmentTree(const vector<long long>& a):length(int(a.size())){while(size<length)size*=2;t.assign(2*size,identity());for(int i=0;i<length;i++)t[size+i]=normalize(a[i]);for(int i=size-1;i;i--)t[i]=op(t[2*i],t[2*i+1]);}void set(int i,long long x){if(i<0||i>=length)throw runtime_error("index out of range");i+=size;t[i]=normalize(x);while(i>>=1)t[i]=op(t[2*i],t[2*i+1]);}long long query(int l,int r)const{if(l<0||r<l||r>length)throw runtime_error("invalid half-open range");long long a=identity(),b=identity();for(l+=size,r+=size;l<r;l>>=1,r>>=1){if(l&1)a=op(a,t[l++]);if(r&1)b=op(t[--r],b);}return op(a,b);}};\n`;
   body='validate_ranges(qs,int(data.size()));SegmentTree tree(data);for(auto q:qs)answer[q.id]=mint(tree.query(q.n,q.m+1));';
  }
  if(p.id==='sparse'){const op=p.op==='gcd'?'std::gcd(a,b)':'std::'+p.op+'(a,b)';body=`validate_ranges(qs,int(data.size()));int L=int(data.size());auto op=[](long long a,long long b){return ${op};};vector<int> lg(L+1);for(int i=2;i<=L;i++)lg[i]=lg[i/2]+1;vector<vector<long long>> st(lg[L]+1,vector<long long>(L));st[0]=data;${p.op==='gcd'?'for(auto& x:st[0])x=llabs(x);':''}for(int k=1;k<=lg[L];k++)for(int i=0;i+(1<<k)<=L;i++)st[k][i]=op(st[k-1][i],st[k-1][i+(1<<(k-1))]);for(auto q:qs){int k=lg[q.m-q.n+1];answer[q.id]=mint(op(st[k][q.n],st[k][q.m-(1<<k)+1]));}`;}
  if(p.id==='distinct-mo'||p.id==='distinct-fenwick'){
   body='validate_ranges(qs,int(data.size()));int L=int(data.size());auto sorted=data;sort(sorted.begin(),sorted.end());sorted.erase(unique(sorted.begin(),sorted.end()),sorted.end());vector<int> a(L);for(int i=0;i<L;i++)a[i]=lower_bound(sorted.begin(),sorted.end(),data[i])-sorted.begin();';
   if(p.id==='distinct-mo')body+='int B=max(1,int(L/sqrt(max(1,int(qs.size())))));sort(qs.begin(),qs.end(),[&](Query a,Query b){int x=a.n/B,y=b.n/B;return x!=y?x<y:(x&1?a.m>b.m:a.m<b.m);});vector<int> freq(sorted.size());int l=0,r=-1,count=0;auto add=[&](int i){if(freq[a[i]]++==0)count++;};auto remove=[&](int i){if(--freq[a[i]]==0)count--;};for(auto q:qs){while(l>q.n)add(--l);while(r<q.m)add(++r);while(l<q.n)remove(l++);while(r>q.m)remove(r--);answer[q.id]=count;}';
   else {defs+=fenwick;body+='sort(qs.begin(),qs.end(),[](Query a,Query b){return a.m<b.m;});Fenwick bit(vector<long long>(L,0));vector<int> last(sorted.size(),-1);int r=-1;for(auto q:qs){while(r<q.m){r++;if(last[a[r]]>=0)bit.add(last[a[r]],-1);bit.add(r,1);last[a[r]]=r;}answer[q.id]=bit.prefix(q.m+1)-bit.prefix(q.n);}';}
  }
 }
 if(p.id==='binomial-mo')body=maxcoord+'check_prefix(U);Comb comb;comb.ensure(U);for(auto& q:qs)q.m=min(q.m,q.n);int B=max(1,int((U+1)/sqrt(max(1,int(qs.size())))));sort(qs.begin(),qs.end(),[&](Query a,Query b){int x=a.n/B,y=b.n/B;return x!=y?x<y:(x&1?a.m>b.m:a.m<b.m);});long long n=0,m=0;mint value=1,half=mint(2).inv();for(auto q:qs){while(n<q.n){value=mint(2)*value-comb.choose(n,m);n++;}while(n>q.n){n--;value=(value+comb.choose(n,m))*half;}while(m<q.m){m++;value+=comb.choose(n,m);}while(m>q.m){value-=comb.choose(n,m);m--;}answer[q.id]=value;}';
 if(p.id==='row-dp'){
  let formula=p.function==='stirling2'?'prev[j-1]+mint(j)*prev[j]':p.function==='stirling1'?'prev[j-1]+mint(i-1)*prev[j]':p.function==='stirling1s'?'prev[j-1]-mint(i-1)*prev[j]':'mint(j+1)*prev[j]+mint(i-j)*prev[j-1]';
  body=maxcoord+'V=min(U,V);if((__int128(U)+1)*(V+1)>30000000)throw runtime_error("DP work limit exceeded; select NTT for Stirling second kind");sort(qs.begin(),qs.end(),[](Query a,Query b){return a.n<b.n;});Poly prev(V+1);prev[0]=1;long long i=0;for(auto q:qs){while(i<q.n){i++;Poly next(V+1);'+(p.function==='eulerian'?'next[0]=1;':'')+'for(int j=1;j<=min(i,V);j++)next[j]='+formula+';prev=move(next);}answer[q.id]=q.m>V?mint(0):prev[q.m];}';
 }
 if(p.id==='stirling-fps')body='long long V=0;for(auto q:qs)V=max(V,min(q.n,q.m));'+'check_prefix(V);Poly fac,ifac;factorial_tables(int(V),fac,ifac);sort(qs.begin(),qs.end(),[](Query a,Query b){return a.n<b.n;});for(size_t begin=0;begin<qs.size();){size_t end=begin;long long n=qs[begin].n,K=0;while(end<qs.size()&&qs[end].n==n){K=max(K,min(n,qs[end].m));end++;}Poly a(K+1),b(K+1);for(int i=0;i<=K;i++){a[i]=mint(i).pow(n)*ifac[i];b[i]=(i%2?-ifac[i]:ifac[i]);}Poly row=mul(a,b);for(size_t i=begin;i<end;i++)answer[qs[i].id]=qs[i].m>n?mint(0):row[qs[i].m];begin=end;}';
 if(p.id==='floor-sum'){
  defs+=`mint floor_sum_mod(unsigned long long n,unsigned long long m,unsigned long long a,unsigned long long b){if(!m)throw runtime_error("m must be positive");using Wide=unsigned __int128;Wide answer=0;for(;;){if(a>=m){answer+=Wide(n)*(n? n-1:0)/2*(a/m);a%=m;}if(b>=m){answer+=Wide(n)*(b/m);b%=m;}Wide top=Wide(a)*n+b;if(top<m)break;n=(unsigned long long)(top/m);b=(unsigned long long)(top%m);swap(a,m);}return mint((long long)(answer%MOD));}\n`;
  body='for(auto q:qs)answer[q.id]=floor_sum_mod(q.n,q.m,'+p.a.a+'ULL,'+p.b.a+'ULL);';
 }
 if(p.id==='quotient'){
  if(p.weight!=='one'){defs+=sieve;body='long long U=0;for(auto q:qs)U=max(U,min(q.n,q.m));check_prefix(U);auto weights=arithmetic_sieve(int(U),'+(p.weight==='totient'?'true':'false')+');Poly pref(U+1);for(int i=1;i<=U;i++)pref[i]=pref[i-1]+weights[i];';}
  body+='for(auto q:qs){mint value=0;long long limit=min(q.n,q.m);for(long long l=1,r;l<=limit;l=r+1){long long a=q.n/l,b=q.m/l;r=min(q.n/a,q.m/b);mint weight='+(p.weight==='one'?'mint(r-l+1)':'pref[r]-pref[l-1]')+';value+=weight*mint(a)*mint(b);}answer[q.id]=value;}';
 }
 if(p.id==='separable'){const a=seq(p.left),b=seq(p.right);body=maxcoord+'check_prefix(U);check_prefix(V);Poly left='+a('int(U)')+',right='+b('int(V)')+';for(int i=1;i<=U;i++)left[i]+=left[i-1];for(int j=1;j<=V;j++)right[j]+=right[j-1];for(auto q:qs)answer[q.id]=left[q.n]*right[q.m];';}
 if(p.id==='prefix2d'){aliases={...mapping,i:'i',j:'j'};body=maxcoord+'if((__int128(U)+2)*(V+2)>4000000)throw runtime_error("2D table exceeds 4000000 cells");Comb comb;int stride=int(V)+2;Poly pref((U+2)*stride);for(int i=0;i<=U;i++)for(int j=0;j<=V;j++)pref[(i+1)*stride+j+1]='+expr(p.cell)+'+pref[i*stride+j+1]+pref[(i+1)*stride+j]-pref[i*stride+j];for(auto q:qs)answer[q.id]=pref[(q.n+1)*stride+q.m+1];';}
 if(p.id==='sequence-expression'){
  let pre='',serial=0,lookups=new Set();function emit(node){if(node.kind==='direct')return expr(node.ast);if(node.kind==='constant')return 'mint('+lit(node.value)+')';if(node.kind==='neg')return '(-'+emit(node.child)+')';if(node.kind==='combine')return '('+emit(node.left)+node.op+emit(node.right)+')';let name='cached_'+serial++,make=seq(node.sequence),limit='maximum_'+mapping[node.variable];lookups.add(mapping[node.variable]);pre+='Poly '+name+'='+make('int('+limit+')')+';';return name+'[q.'+mapping[node.variable]+']';}
  let expression=emit(p.expression);body=[...lookups].map(f=>'long long maximum_'+f+'=0;for(auto q:qs)maximum_'+f+'=max(maximum_'+f+',q.'+f+');check_prefix(maximum_'+f+');').join('')+pre+(/\bcomb\b/.test(expression)?'Comb comb;':'')+'for(auto q:qs){'+bindings+'answer[q.id]='+expression+';}';
 }

 if(p.id==='binomial-min-mo'){
  defs+=`struct PrefixQuery {long long n,m;int id;};
vector<mint> binomial_prefix_queries(vector<PrefixQuery> qs,Comb& comb,long long U){vector<mint> answer(qs.size());for(auto& q:qs)q.m=min(q.m,q.n);int B=max(1,int((U+1)/sqrt(max(1,int(qs.size())))));sort(qs.begin(),qs.end(),[&](PrefixQuery a,PrefixQuery b){int x=a.n/B,y=b.n/B;return x!=y?x<y:(x&1?a.m>b.m:a.m<b.m);});long long n=0,m=0;mint value=1,half=mint(2).inv();for(auto q:qs){while(n<q.n){value=mint(2)*value-comb.choose(n,m);n++;}while(n>q.n){n--;value=(value+comb.choose(n,m))*half;}while(m<q.m){m++;value+=comb.choose(n,m);}while(m>q.m){value-=comb.choose(n,m);m--;}answer[q.id]=value;}return answer;}
`;
  body='long long U=0;for(auto q:qs)U=max(U,q.n+q.m);check_prefix(U);Comb comb;comb.ensure(U);Poly power(U+1,1);for(int i=1;i<=U;i++)power[i]=power[i-1]*mint(2);vector<PrefixQuery> sub;for(auto q:qs){sub.push_back({q.n+q.m,q.m,int(sub.size())});'+(p.truncated?'sub.push_back({q.m,q.n,int(sub.size())});':'')+'}auto partial=binomial_prefix_queries(sub,comb,U);mint half=mint(2).inv();for(auto q:qs){long long N=q.n+q.m;mint H=0;if(N)H=mint(q.m)*power[N]*half+mint(q.n-q.m)*partial['+(p.truncated?'2*':'')+'q.id]*half-mint(N)*comb.choose(N-1,q.m)*half;answer[q.id]=H'+(p.truncated?'-mint(q.n)*power[q.n]*half*(power[q.m]-partial[2*q.id+1])':'')+';}';
 }
 if(p.kind==='project'){
  const child=embed(p.childAst,p.child,['n','m']);body='vector<'+child.name+'::Query> sub;for(auto q:qs)sub.push_back({q.'+mapping[p.coordinates[0]]+',q.'+mapping[p.coordinates[1]]+',q.id});auto values='+child.name+'::solve_queries(sub,data);for(size_t i=0;i<qs.size();i++)answer[i]=mint(values[i].v);';
 }
 if(p.id==='compose'){
  const values=p.parts.map((part,i)=>{const c=embed(part.ast,part.choice,part.variables);body+='vector<'+c.name+'::Query> sub'+i+';for(auto q:qs)sub'+i+'.push_back({'+part.variables.map(x=>mapping[x]?'q.'+mapping[x]:'0').join(',')+',q.id});auto values'+i+'='+c.name+'::solve_queries(sub'+i+',data);';return 'mint(values'+i+'[i].v)'});
  body+='for(size_t i=0;i<qs.size();i++)answer[i]='+ (p.op==='neg'?'-'+values[0]:values.join(p.op))+';';
 }
 if(p.id==='prefix-nd'){
  const D=p.axes.length;aliases={...mapping,...Object.fromEntries(p.indices.map((x,i)=>[x,'cell_'+i]))};
  body='vector<long long> dims('+D+',1),stride('+D+',1);for(auto q:qs){'+p.axes.map((x,i)=>'dims['+i+']=max(dims['+i+'],q.'+mapping[x]+'+1);').join('')+'}long long total=1;for(int d='+D+'-1;d>=0;d--){if(dims[d]>4000000/total)throw runtime_error("ND table exceeds 4000000 cells");stride[d]=total;total*=dims[d];}Comb comb;Poly pref(total);for(long long flat=0;flat<total;flat++){'+p.indices.map((x,i)=>'long long cell_'+i+'=(flat/stride['+i+'])%dims['+i+'];').join('')+'pref[flat]='+expr(p.cell)+';}for(int d=0;d<'+D+';d++)for(long long flat=0;flat<total;flat++)if((flat/stride[d])%dims[d])pref[flat]+=pref[flat-stride[d]];for(auto q:qs)answer[q.id]=pref['+p.axes.map((x,i)=>'q.'+mapping[x]+'*stride['+i+']').join('+')+'];';
 }
 if(!body)throw Error('未対応の生成プラン: '+p.id);
 const comment='// C++17 (GCC / Clang: __int128), modulo 998244353.\n// Expression: '+result.source.replace(/[\r\n]/g,' ')+'\n// Fixed parameters: '+Object.entries(result.params||{}).map(([k,v])=>k+'='+v).join(', ')+'\n// Algorithm: '+p.name+'\n// Cost: '+p.cost+'\n// Conditions: '+p.condition+'\n// Queries are inclusive [n,m] for array/range expressions.\n// Coordinate order: '+names.join(' ')+'\n// Input: '+(target==='grid'?'One inclusive upper limit per coordinate; output coordinates and value.':(p.array?'L, L array values, ':'')+'Q, then Q rows in coordinate order.')+'\n// All query coordinates: 0..10^12; Q <= 10^6. Method-specific limits are checked.\n// Answers retain input order. solve_queries accepts an optional data vector.\n';
 let helpers=common.replace('long long n,m;','long long '+fields.join(',')+';');if(!legacy){helpers=helpers.replace(/^void validate_ranges.*\n/m,'');helpers=helpers.replace('q.n<0||q.m<0||q.n>1000000000000LL||q.m>1000000000000LL',fields.map(f=>'q.'+f+'<0||q.'+f+'>1000000000000LL').join('||'));}if(!/\bcomb\b/.test(body))helpers=helpers.replace(/^struct Comb .*\n/m,'');if(!/lcm_mod\(/.test(body))helpers=helpers.replace(/^mint lcm_mod.*\n/m,'');if(!/checked_signed\(/.test(body))helpers=helpers.replace(/^long long checked_signed.*\n/m,'');if(!/checked_nonnegative\(/.test(body))helpers=helpers.replace(/^u64 checked_nonnegative.*\n/m,'');
 let output=comment+'#include <climits>\n#include <numeric>\n#include <utility>\n'+library+'\n'+helpers+'\n'+defs+'\nvector<mint> solve_queries(vector<Query> qs,const vector<long long>& data={}){validate_queries(qs);if(data.size()>=(1<<21))throw runtime_error("array length limit");for(auto x:data)if(x < -1000000000000LL||x>1000000000000LL)throw runtime_error("array value out of range");vector<mint> answer(qs.size());if(qs.empty())return answer;'+body+'return answer;}\n#ifndef SIGMA_NO_MAIN\nint main(){try{vector<long long> data;'+(p.array?'int L;if(!(cin>>L)||L<=0||L>=(1<<21))throw runtime_error("invalid array length");data.resize(L);for(auto& x:data)if(!(cin>>x)||x < -1000000000000LL||x>1000000000000LL)throw runtime_error("invalid array value");':'')+'int Q;if(!(cin>>Q)||Q<0||Q>1000000)throw runtime_error("invalid Q");vector<Query> qs(Q);for(int i=0;i<Q;i++){if(!(cin>>'+fields.map(f=>'qs[i].'+f).join('>>')+'))throw runtime_error("invalid query");qs[i].id=i;}for(auto x:solve_queries(qs,data))cout<<x.v<<"\\n";}catch(const exception& e){cerr<<e.what()<<"\\n";return 1;}}\n#endif\n';
 if(target==='grid'){
  if(p.array||['prefix','product-prefix','floor-sum'].includes(p.id))throw Error('この手法は0始まりの矩形全表に対応しません。クエリ列を選択してください。');
  output=output.split('#ifndef SIGMA_NO_MAIN')[0]+'#ifndef SIGMA_NO_MAIN\nint main(){try{vector<long long> limit('+names.length+'),stride('+names.length+');long long total=1;for(auto& x:limit)if(!(cin>>x)||x<0||x>=1000000)throw runtime_error("invalid grid limit");for(int d='+names.length+'-1;d>=0;d--){if(limit[d]+1>1000000/total)throw runtime_error("table limit: 1000000 cells");stride[d]=total;total*=limit[d]+1;}vector<Query> qs;for(int flat=0;flat<total;flat++)qs.push_back({'+fields.map((f,i)=>'(flat/stride['+i+'])%(limit['+i+']+1)').join(',')+',flat});auto a=solve_queries(qs);for(size_t i=0;i<a.size();i++)cout'+fields.map(f=>'<<qs[i].'+f+'<<" "').join('')+'<<a[i].v<<"\\n";}catch(const exception& e){cerr<<e.what()<<"\\n";return 1;}}\n#endif\n';
 }
 return output.replace(/\n{3,}/g,'\n\n');
}
const common=String.raw`
struct Query {long long n,m;int id;};
void check_prefix(long long n){if(n<0||n>=(1LL<<21))throw runtime_error("precomputation requires index < 2^21");}
void validate_queries(vector<Query>& qs){if(qs.size()>1000000)throw runtime_error("Q exceeds 1000000");for(size_t i=0;i<qs.size();i++){auto& q=qs[i];if(q.n<0||q.m<0||q.n>1000000000000LL||q.m>1000000000000LL)throw runtime_error("coordinates must be in 0..10^12");q.id=int(i);}}
void validate_ranges(const vector<Query>& qs,int L){if(L<=0||L>=(1<<21))throw runtime_error("invalid array length");for(auto q:qs)if(q.n>q.m||q.m>=L)throw runtime_error("range requires 0 <= n <= m < length");}
long long checked_signed(__int128 x){if(x< -1000000000000LL||x>1000000000000LL)throw runtime_error("integer expression outside supported range");return (long long)x;}
u64 checked_nonnegative(__int128 x){if(x<0||x>1000000000000LL)throw runtime_error("power must be in 0..10^12");return (u64)x;}
mint lcm_mod(long long a,long long b){long long g=std::gcd(a,b);return g?mint(llabs(a/g))*mint(llabs(b)):mint(0);}
struct Comb {Poly fac{1},ifac{1};void ensure(long long n){check_prefix(n);if(n<(long long)fac.size())return;int old=int(fac.size()),N=max((int)n,min((1<<21)-1,old*2));fac.resize(N+1);ifac.resize(N+1);for(int i=old;i<=N;i++)fac[i]=fac[i-1]*mint(i);ifac[N]=fac[N].inv();for(int i=N;i>0;i--)ifac[i-1]=ifac[i]*mint(i);}mint factorial(long long n){ensure(n);return fac[n];}mint choose(long long n,long long k){if(n<0)throw runtime_error("binomial upper argument must be nonnegative");if(k<0||k>n)return 0;ensure(n);return fac[n]*ifac[k]*ifac[n-k];}mint falling(long long n,long long k){if(n<0||k<0)throw runtime_error("falling requires nonnegative arguments");if(k>n)return 0;ensure(n);return fac[n]*ifac[n-k];}mint rising(long long n,long long k){if(n<0||k<0)throw runtime_error("rising requires nonnegative arguments");if(!k)return 1;if(!n)return 0;ensure(n+k-1);return fac[n+k-1]*ifac[n-1];}};
`;
const fenwick=String.raw`struct Fenwick {int length;Poly t;Fenwick(const vector<long long>& a):length(int(a.size())),t(length+1){for(int i=1;i<=length;i++){t[i]+=mint(a[i-1]);if(i+(i&-i)<=length)t[i+(i&-i)]+=t[i];}}void add(int i,mint x){if(i<0||i>=length)throw runtime_error("index out of range");for(i++;i<=length;i+=i&-i)t[i]+=x;}mint prefix(int end)const{if(end<0||end>length)throw runtime_error("prefix endpoint out of range");mint r=0;for(;end;end-=end&-end)r+=t[end];return r;}};
`;
const sieve=String.raw`Poly arithmetic_sieve(int N,bool phi){vector<int> primes,least(N+1),f(N+1);if(N)f[1]=1;for(int i=2;i<=N;i++){if(!least[i]){least[i]=i;primes.push_back(i);f[i]=phi?i-1:-1;}for(int p:primes){if(1LL*i*p>N)break;least[i*p]=p;if(i%p==0){f[i*p]=phi?f[i]*p:0;break;}f[i*p]=phi?f[i]*(p-1):-f[i];}}Poly out(N+1);for(int i=1;i<=N;i++)out[i]=f[i];return out;}
`;
root.SigmaQueryCPP={generate};if(typeof module!=='undefined')module.exports=root.SigmaQueryCPP;
})(typeof globalThis!=='undefined'?globalThis:this);
