(function(root){
'use strict';
const E=root.SigmaEngine||(typeof require!=='undefined'?require('./engine.js'):null),O=root.SigmaOptimize||(typeof require!=='undefined'?require('./optimize.js'):null),q=E.q;
const num=x=>({type:'num',value:q(x)}),v=name=>({type:'var',name}),bin=(op,left,right)=>({type:'bin',op,left,right}),call=(name,...args)=>({type:'call',name,args}),same=(a,b)=>E.format(a)===E.format(b),isnum=(a,n)=>a.type==='num'&&a.value.eq(n);
const flat=(a,op='*')=>a.type==='bin'&&a.op===op?[...flat(a.left,op),...flat(a.right,op)]:[a],join=(a,op='*')=>a.reduce((x,y)=>x?bin(op,x,y):y,null)||num(op==='*'?1:0);
function terms(a,domain){return O.multivariate(a,[...domain])}
function nonnegative(a,domain){let p=terms(a,domain);return p&&p.every(t=>t.coefficient.b===1n&&t.coefficient.a>=0n&&Object.keys(t.powers).every(x=>domain.has(x)))}
function equal(a,b){const p=O.multivariate(bin('-',a,b),[...new Set([...E.freeVariables(a),...E.freeVariables(b)])]);return p?p.length===0:same(a,b)}
function le(a,b,domain){return equal(a,b)||!!nonnegative(bin('-',b,a),domain)}
function fromTerms(ts){return join(ts.map(t=>join([num(t.coefficient),...Object.entries(t.powers).map(([x,k])=>k===1?v(x):bin('^',v(x),num(k)))])),'+')}
function algebra(a){let p=O.multivariate(a,E.freeVariables(a));return p?basic(fromTerms(p)):basic(a)}
function basic(a){if(a.type==='neg'){let x=basic(a.x);return x.type==='num'?num(x.value.neg()):x.type==='neg'?x.x:{...a,x}}if(a.type==='call')return {...a,args:a.args.map(basic)};if(a.type!=='bin')return a;let l=basic(a.left),r=basic(a.right);a={...a,left:l,right:r};if(l.type==='num'&&r.type==='num'){try{return num(E.evaluate(a,0))}catch{return a}}
 if(['+','*'].includes(a.op)){let c=q(a.op==='*'?1:0),rest=[];for(const f of flat(a,a.op)){if(f.type==='num')c=a.op==='*'?c.mul(f.value):c.add(f.value);else rest.push(f)}if(a.op==='*'&&c.zero())return num(0);rest.sort((a,b)=>E.format(a).localeCompare(E.format(b)));if(!c.eq(a.op==='*'?1:0)||!rest.length)rest.unshift(num(c));return join(rest,a.op)}if(a.op==='-'&&isnum(r,0)||a.op==='/'&&isnum(r,1)||a.op==='^'&&isnum(r,1))return l;return a;
}
function affine(a,k){const ts=O.multivariate(a,E.freeVariables(a));if(!ts)return null;let slope=q(0),rest=[];for(const t of ts){let d=t.powers[k]||0;if(!d)rest.push(t);else if(d===1&&Object.keys(t.powers).length===1)slope=slope.add(t.coefficient);else return null}return {slope,offset:basic(fromTerms(rest))}}
function everywhere(a,k,domain){if(a.type==='num'||a.type==='var')return true;if(a.type==='neg')return everywhere(a.x,k,domain);if(a.type==='bin')return everywhere(a.left,k,domain)&&everywhere(a.right,k,domain)&&(a.op!=='/'||a.right.type==='num'&&!a.right.value.zero())&&(a.op!=='^'||a.right.type==='num'&&a.right.value.b===1n&&a.right.value.a>=0n);return a.type==='call'&&(['min','max','abs','gcd','lcm'].includes(a.name)&&a.args.every(x=>everywhere(x,k,domain))||a.name==='binomial'&&nonnegative(a.args[0],domain)&&a.args.every(x=>everywhere(x,k,domain)));}
function binomialMoment(a,domain=new Set(E.freeVariables(a))){if(a.type!=='call'||a.name!=='sum')return null;const [body,k,lo,hi]=a.args;if(!isnum(lo,0)||O.free(hi,k.name)||!nonnegative(hi,domain))return null;let factors=flat(body),bi=factors.find(f=>f.type==='call'&&f.name==='binomial'&&equal(f.args[0],hi)&&equal(f.args[1],k));if(!bi)return null;factors=factors.filter(x=>x!==bi);let sign=null;for(const f of factors)if(f.type==='bin'&&f.op==='^'&&f.left.type==='num'&&f.left.value.eq(-1)&&(equal(f.right,k)||equal(f.right,bin('-',hi,k)))){sign=equal(f.right,k)?'k':'reverse';factors=factors.filter(x=>x!==f);break}
 const ts=O.multivariate(join(factors),[...domain,k.name]);if(!ts||ts.some(t=>(t.powers[k.name]||0)>12))return null;let coeff=Array.from({length:Math.max(0,...ts.map(t=>t.powers[k.name]||0))+1},()=>num(0));for(const t of ts){let d=t.powers[k.name]||0,powers={...t.powers};delete powers[k.name];const c=fromTerms([{...t,powers}]);for(let j=0;j<=d;j++)coeff[j]=basic(bin('+',coeff[j],bin('*',c,num(E.fn('stirling2',[q(d),q(j)])))))}return {upper:hi,coeff,sign};
}
function vandermonde(a,domain){if(a.type!=='call'||a.name!=='sum')return null;const [body,k,lo,hi]=a.args,factors=flat(body);if(factors.length!==2||factors.some(f=>f.type!=='call'||f.name!=='binomial'||O.free(f.args[0],k.name)||!nonnegative(f.args[0],domain)))return null;const [f,g]=factors,[A,B]=[f.args[0],g.args[0]],x=affine(f.args[1],k.name),y=affine(g.args[1],k.name);if(!x||!y||![x.slope,y.slope].every(s=>s.eq(1)||s.eq(-1)))return null;
 const bound=(a,t)=>t.slope.eq(1)?[algebra(bin('*',num(-1),t.offset)),algebra(bin('-',a,t.offset))]:[algebra(bin('-',t.offset,a)),t.offset];const [L,U]=bound(A,x),[M,V]=bound(B,y);
 const lower=le(lo,L,domain)||le(lo,M,domain)||lo.type==='call'&&lo.name==='max'&&((equal(lo.args[0],L)&&equal(lo.args[1],M))||(equal(lo.args[1],L)&&equal(lo.args[0],M)));
 const upper=le(U,hi,domain)||le(V,hi,domain)||hi.type==='call'&&hi.name==='min'&&((equal(hi.args[0],U)&&equal(hi.args[1],V))||(equal(hi.args[1],U)&&equal(hi.args[0],V)));
 if(!lower||!upper)return null;return call('binomial',algebra(bin('+',A,B)),algebra(x.slope.eq(y.slope)?bin('+',B,bin('-',x.offset,y.offset)):bin('+',x.offset,y.offset)));
}
// A bounded hypergeometric antidifference search: Q(k+1) A(k)-Q(k) B(k)=P(k) B(k).
// Successful candidates are checked as exact polynomial identities, not sampled.
const trim=a=>{while(a.length>1&&a.at(-1).zero())a.pop();return a},add=(a,b)=>trim(Array.from({length:Math.max(a.length,b.length)},(_,i)=>(a[i]||q(0)).add(b[i]||q(0)))),scale=(a,c)=>a.map(x=>x.mul(c));
function mul(a,b){let c=Array.from({length:a.length+b.length-1},()=>q(0));for(let i=0;i<a.length;i++)for(let j=0;j<b.length;j++)c[i+j]=c[i+j].add(a[i].mul(b[j]));return trim(c)}
function shift(a){let r=[q(0)],p=[q(1)];for(const c of a){r=add(r,scale(p,c));p=mul(p,[q(1),q(1)])}return r}
function polynomialIn(a,k){if(E.freeVariables(a).some(x=>x!==k))return null;return O.polynomial(O.substitute(a,k,v('n')))}
function polyAST(p,k){return basic(join(p.map((c,i)=>bin('*',num(c),i?bin('^',v(k),num(i)):num(1))),'+'))}
function antidifference(body,k){let P=[q(1)],A=[q(1)],B=[q(1)],hyper=[];for(const f of flat(body)){let p=polynomialIn(f,k);if(p){P=mul(P,p);continue}if(f.type==='call'&&f.name==='factorial'){let t=polynomialIn(f.args[0],k);if(!t||t.length!==2||t.some(x=>x.b!==1n)||t[0].a<0n||t[1].a<1n||t[1].a>8n)return null;for(let j=1;j<=Number(t[1].a);j++)A=mul(A,[t[0].add(j),t[1]]);hyper.push(f);continue}if(f.type==='bin'&&f.op==='^'&&f.left.type==='num'&&!f.left.value.zero()){let t=polynomialIn(f.right,k);if(!t||t.length>2||t.some(x=>x.b!==1n)||Math.abs(Number(t[1]?.a||0n))>12)return null;A=scale(A,E.evaluate(bin('^',f.left,num(t[1]||0)),0));hyper.push(f);continue}return null}
 if(!hyper.length||A.length>25||P.length>25)return null;const rhs=mul(P,B);
 for(let d=0;d<=12;d++){let columns=[];for(let j=0;j<=d;j++){let mon=Array.from({length:j+1},(_,i)=>q(i===j?1:0));columns.push(add(mul(A,shift(mon)),scale(mul(B,mon),-1)))}let length=Math.max(rhs.length,...columns.map(x=>x.length)),rows=Array.from({length:length},(_,i)=>[...columns.map(p=>p[i]||q(0)),(rhs[i]||q(0)).neg()]);const x=E.nullVector(rows,d+2);if(!x||x.at(-1).zero())continue;let Q=x.slice(0,-1).map(c=>c.div(x.at(-1))),check=add(add(mul(A,shift(Q)),scale(mul(B,Q),-1)),scale(rhs,-1));if(check.every(c=>c.zero()))return {ast:basic(bin('*',polyAST(Q,k),join(hyper))),certificate:'A(k)Q(k+1)−B(k)Q(k)=B(k)P(k) を有理数係数多項式として厳密検証'};
 }return null;
}
function normalize(ast){let steps=[],domain=new Set(E.freeVariables(ast)),budget=0;
 function note(before,after,reason){after=basic(after);if(!same(before,after)){steps.push({before:E.format(before),after:E.format(after),reason,proven:true});return after}return before}
 function walk(a,scope,depth=0){if(depth>40||++budget>12000)return a;if(a.type==='num'||a.type==='var')return a;if(a.type==='neg')return basic({...a,x:walk(a.x,scope,depth+1)});if(a.type==='bin'){let b=basic({...a,left:walk(a.left,scope,depth+1),right:walk(a.right,scope,depth+1)});if(b.type==='bin'&&b.op==='^'&&b.left.type==='num'&&!b.left.value.zero()){const names=E.freeVariables(b.right);if(names.length===1){const t=affine(b.right,names[0]);if(t&&t.slope.eq(1)&&t.offset.type==='num'&&t.offset.value.b===1n&&!t.offset.value.zero()&&t.offset.value.a>=-1000n&&t.offset.value.a<=1000n)return note(b,bin('*',num(E.evaluate(bin('^',b.left,t.offset),0)),bin('^',b.left,v(names[0]))),'指数の定数シフトを定数因子へ分離');}}return b;}
  if(!['sum','prod'].includes(a.name)){a={...a,args:a.args.map(x=>walk(x,scope,depth+1))};if(a.name==='binomial'&&nonnegative(a.args[0],scope)){const upper=a.args[0],lower=a.args[1];if(lower.type==='bin'&&lower.op==='-'&&equal(lower.left,upper))return note(a,call('binomial',upper,lower.right),'二項係数の対称性（上側は非負整数）')}return a}
  let [body,k,lo,hi]=a.args;lo=walk(lo,scope,depth+1);hi=walk(hi,scope,depth+1);let inner=new Set(scope);inner.delete(k.name);if(nonnegative(lo,scope))inner.add(k.name);body=walk(body,inner,depth+1);a={...a,args:[body,k,lo,hi]};if(a.name!=='sum')return a;
  if(body.type==='call'&&body.name==='sum'&&(isnum(lo,0)||isnum(lo,1))&&nonnegative(hi,scope)){const [cell,j,L,H]=body.args;if(k.name!==j.name&&(isnum(L,0)||isnum(L,1))&&nonnegative(H,scope)&&!O.free(H,k.name)&&!O.free(hi,j.name)&&!O.free(hi,k.name)&&cell.type==='call'&&cell.name==='gcd'&&((same(cell.args[0],k)&&same(cell.args[1],j))||(same(cell.args[1],k)&&same(cell.args[0],j)))){let name='_d';while(E.freeVariables(a).includes(name))name+='_';const d=v(name);let result=call('sum',join([call('totient',d),call('floor',bin('/',hi,d)),call('floor',bin('/',H,d))]),d,num(1),call('min',hi,H));const triangular=x=>bin('/',bin('*',x,bin('+',x,num(1))),num(2));if(isnum(L,0))result=bin('+',result,triangular(hi));if(isnum(lo,0))result=bin('+',result,triangular(H));return note(a,result,'gcd(i,j)=Σ_{d|i,d|j} φ(d) で約数和へ交換。0の境界項は別に加算');}}
  let vm=vandermonde(a,scope);if(vm)return note(a,vm,'Vandermonde（シフト・反転と二項係数の非零範囲を確認）');
  let moment=binomialMoment(a,scope);if(moment&&!moment.sign){const terms=moment.coeff.map((c,j)=>bin('*',c,bin('/',j?call('falling',hi,num(j)):num(1),num(2n**BigInt(j)))));return note(a,bin('*',bin('^',num(2),hi),join(terms,'+')),'k^dをStirling第二種×下降階乗へ展開し、重み付き二項和を消去')}
  if(body.type==='bin'&&body.op==='-'&&equal(body.left,O.substitute(body.right,k.name,bin('+',k,num(1))))&&nonnegative(bin('-',hi,lo),scope))return note(a,bin('-',O.substitute(body.right,k.name,bin('+',hi,num(1))),O.substitute(body.right,k.name,lo)),'前進差分の望遠鏡和');
  if(nonnegative(lo,scope)&&nonnegative(bin('+',bin('-',hi,lo),num(1)),scope)){const anti=antidifference(body,k.name);if(anti)return note(a,bin('-',O.substitute(anti.ast,k.name,bin('+',hi,num(1))),O.substitute(anti.ast,k.name,lo)),'超幾何項の原始差分（次数12以下の多項式証明書）。'+anti.certificate)}
  const factors=flat(body),outside=factors.filter(f=>!O.free(f,k.name)),inside=factors.filter(f=>O.free(f,k.name));if(outside.length&&inside.length&&(nonnegative(bin('-',hi,lo),scope)||outside.every(f=>everywhere(f,k.name,scope))))return note(a,bin('*',join(outside),call('sum',join(inside),k,lo,hi)),'添字に依存しない因子を和の外へ移動');
  if(isnum(lo,0)&&hi.type==='call'&&hi.name==='min'&&everywhere(body,k.name,inner)){for(const upper of hi.args){const choose=factors.find(f=>f.type==='call'&&f.name==='binomial'&&equal(f.args[0],upper)&&equal(f.args[1],k));const other=hi.args.find(x=>x!==upper);if(choose&&nonnegative(upper,scope)&&nonnegative(other,scope))return note(a,call('sum',body,k,lo,other),'二項係数が上側添字より外で0になることを使って和の上限を拡大')}}
  return a;
 }
 let current=ast;for(let pass=0;pass<6;pass++){let next=walk(current,domain);if(E.format(next).length>14000)break;if(same(current,next))break;current=next}if(!same(ast,current)&&!steps.length)steps.push({before:E.format(ast),after:E.format(current),reason:'加算・乗算の結合と定数因子・項の順序を正規化',proven:true});return {ast:current,steps};
}
function variants(ast){const first=normalize(ast),out=[first],seen=new Set([E.format(first.ast)]);function add(a,path,reason){let n=normalize(a),key=E.format(n.ast);if(seen.has(key)||out.length>=12||key.length>14000)return;seen.add(key);out.push({ast:n.ast,steps:[...path,{before:'',after:E.format(a),reason,proven:true},...n.steps]})}
 for(let index=0;index<out.length&&index<6;index++){const {ast:a,steps}=out[index];if(a.type!=='call'||a.name!=='sum')continue;let [body,k,lo,hi]=a.args,scope=new Set(E.freeVariables(a));if(!isnum(lo,0)&&!O.free(lo,k.name))add(call('sum',O.substitute(body,k.name,bin('+',k,lo)),k,num(0),algebra(bin('-',hi,lo))),steps,'添字をk+下限へシフト');if(isnum(lo,0)&&!O.free(hi,k.name)&&nonnegative(hi,scope))add(call('sum',O.substitute(body,k.name,bin('-',hi,k)),k,lo,hi),steps,'添字を上限−kへ反転');
  if(body.type==='call'&&body.name==='sum'){let [cell,j,L,H]=body.args;if(j.name===k.name)continue;if(!O.free(L,k.name)&&!O.free(H,k.name)&&!O.free(lo,j.name)&&!O.free(hi,j.name))add(call('sum',call('sum',cell,k,lo,hi),j,L,H),steps,'独立な有限和の順序を交換');if(isnum(lo,0)&&isnum(L,0)&&equal(H,k)&&!O.free(hi,j.name)&&!O.free(hi,k.name))add(call('sum',call('sum',cell,k,j,hi),j,num(0),hi),steps,'三角領域 0≤j≤i≤N の和の順序を交換');if(isnum(lo,0)&&equal(L,k)&&equal(H,hi)&&!O.free(hi,j.name)&&!O.free(hi,k.name))add(call('sum',call('sum',cell,k,num(0),j),j,num(0),hi),steps,'三角領域 0≤i≤j≤N の和の順序を交換');}
 }return out;
}
function finiteDifference(ast){let m=binomialMoment(ast);if(!m||!m.sign||m.upper.type!=='var'||m.upper.name!=='n'||E.freeVariables(ast).some(x=>x!=='n'))return null;return {kind:'rational',P:m.coeff.map((c,j)=>E.evaluate(c,j).mul(E.fn('factorial',[q(j)])).mul(m.sign==='k'&&j%2?-1:1)),Q:[q(1)],proven:true,certificate:'交代二項和＝有限差分。次数dより大きいnでは0'};}
root.SigmaRewrite={normalize,variants,binomialMoment,finiteDifference,antidifference,equal,nonnegative};if(typeof module!=='undefined')module.exports=root.SigmaRewrite;
})(typeof globalThis!=='undefined'?globalThis:this);
