const E=require('./engine.js'),Q=require('./queries.js'),C=require('./query-cpp.js'),O=require('./optimize.js'),fs=require('fs'),cp=require('child_process'),path=require('path'),os=require('os'),assert=require('assert/strict');
const expressions=['bell(n)+fibonacci(m)','bell(n)*bernoulli(m)','sum(2*k*k+3*m*k,k,0,n)','sum(sum(i*j+i+j,j,0,m),i,0,n)','binomial(n+m,n)','factorial(n)+falling(m,2)+rising(n,3)','gcd(n,m)+lcm(n,m)','sum(binomial(n,k),k,0,m)','stirling1(n,m)','stirling1s(n,m)','stirling2(n,m)','eulerian(n,m)','sum(fibonacci(k),k,n,m)','prod(k-3,k,n,m)','sum(floor((3*k+2)/m),k,0,n-1)','sum(floor(n/k)*floor(m/k),k,1,min(n,m))','sum(totient(k)*floor(n/k)*floor(m/k),k,1,min(n,m))','sum(mobius(k)*floor(n/k)*floor(m/k),k,1,min(n,m))','sum(sum(gcd(i,j),j,0,m),i,0,n)','sum(sum(bell(i)*fibonacci(j),j,0,m),i,0,n)','sum(array(k),k,n,m)','prod(array(k),k,n,m)','distinct(n,m)','range_min(n,m)','range_max(n,m)','range_gcd(n,m)'];
const data=[-4,0,5,5,998244353,12,-4,6,0,1,7,-8,12,12,0,19,8,2,1000000000000,-1000000000000];let cases=[];
for(const source of expressions){let r=Q.analyze(source);assert(r.choices.length,source);for(let plan of r.choices){let points=[];for(let n=0;n<16;n++)for(let m=0;m<16;m++){if(plan.array||['prefix','product-prefix'].includes(plan.id)){if(n>m)continue;}if(plan.id==='floor-sum'&&!m)continue;points.push([n,m]);}if(plan.id==='stirling-fps')for(let k=0;k<=90;k++)points.push([100,k]);points.sort((a,b)=>(a[0]*53+a[1]*17)%37-(b[0]*53+b[1]*17)%37);cases.push({r,plan,points});}}
let cpp='#include <bits/stdc++.h>\n#define SIGMA_NO_MAIN\n';for(let i=0;i<cases.length;i++){let t=cases[i];cpp+='namespace test'+i+' {\n'+C.generate(t.r,t.plan.id).replace(/^#include .*$/gm,'')+'\n}\n';console.log(t.plan.id,t.r.source)}
cpp+='int main(){\n';for(let i=0;i<cases.length;i++){let t=cases[i];cpp+='{std::vector<test'+i+'::Query> qs={'+t.points.map(([n,m],j)=>'{'+[n,m,j].join(',')+'}').join(',')+'};auto result=test'+i+'::solve_queries(qs,{'+data.map(x=>x+'LL').join(',')+'});for(int j=0;j<(int)result.size();j++)std::cout<<"'+i+' "<<j<<" "<<result[j].v<<"\\n";}\n';}cpp+='}\n';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sigma-query-test-')),source=path.join(dir,'test.cpp'),exe=path.join(dir,'test.exe');fs.writeFileSync(source,cpp);try{cp.execFileSync(process.env.CXX||'g++',['-std=c++17','-O2',source,'-o',exe],{stdio:'pipe',timeout:120000});}catch(e){console.error(String(e.stderr));throw e}
const out=cp.execFileSync(exe,[],{encoding:'utf8',timeout:120000});let checks=0;for(let line of out.trim().split(/\r?\n/)){let [i,j,actual]=line.split(' '),t=cases[+i],[n,m]=t.points[+j],want=O.residue(Q.evaluate(t.r.ast,n,m,data.map(String)));assert.equal(actual,String(want),t.plan.id+' '+t.r.source+' '+n+','+m);checks++;}
assert.equal(E.format(Q.bind('sum(m*n,m,0,n)+a',{m:E.q(7),a:E.q(2)},false)),'(sum((m*n),m,0,n)+2)');
assert.equal(String(Q.parameters('n=3').n),'3');assert.throws(()=>Q.points('2 -1'));assert.equal(Q.analyze('sum(binomial(n,k)^3,k,0,m)').choices.length,0);
console.log('PASS query C++ value checks:',checks,'plans:',cases.length);console.log('Artifacts:',dir);
