const E=require('./engine'),O=require('./optimize'),Q=require('./queries'),S=require('./code-output'),F=require('./fast-cpp'),assert=require('assert/strict'),fs=require('fs'),cp=require('child_process'),os=require('os'),path=require('path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sigma-solve-')),cases=[];let expected=[],checks=0;
for(const source of ['sum(k^2,k,0,n)','fibonacci(n)','bell(n)','sum(k*factorial(k),k,0,n)','sum(bell(k)*fibonacci(n-k),k,0,n)']){
 const r=E.analyze(source);for(const mode of ['fast-nth','fast-prefix']){const item=S.sequence(r,mode),index=cases.length;assert(!/int main\s*\(/.test(item.code));let runner='';if(mode==='fast-nth'){runner='for(int n=0;n<22;n++) std::cout << test'+index+'::solve(n) << "\\n";';}else runner='for(auto value:test'+index+'::solve(21)) std::cout << value << "\\n";';for(let n=0;n<22;n++)expected.push(String(O.residue(E.evaluate(r.ast,n))));runner+='try { test'+index+'::solve(-1); return 21; } catch(const std::exception&) {}';cases.push({code:item.code,runner});}
}
const data=[2,0,-2,3,3,0,1,4];
for(const source of ['sum(binomial(n,k),k,0,m)','sum(sum(binomial(n,i)*binomial(m,j)*min(i,j),i,0,n),j,0,n)','a+b*c','auto+class*template','sum(C(n,k+a)*C(m,k+b),k,-a,n-a)','sum(array(k),k,n,m)','prod(array(k),k,n,m)','distinct(n,m)','sum(sum(gcd(i,j),j,1,m),i,1,n)']){
 const r=Q.analyze(source);for(const plan of r.choices){const item=S.queries(r,plan.id),index=cases.length,points=Array.from({length:12},(_,n)=>r.variables.map((_,j)=>plan.array?j?Math.min(7,n%4+3):n%4:(n*(j+1))%6));let runner='{std::vector<test'+index+'::Query> queries={'+points.map(row=>'{'+row.join(',')+'}').join(',')+'};for(auto value:test'+index+'::solve('+(plan.array?'std::vector<long long>{'+data.join(',')+'},':'')+'queries))std::cout<<value<<"\\n";';runner+='if(!test'+index+'::solve('+(plan.array?'std::vector<long long>{'+data.join(',')+'},':'')+'{}).empty())return 22;}';for(const row of points)expected.push(String(O.residue(Q.evaluateAt(r.ast,Object.fromEntries(r.variables.map((x,i)=>[x,row[i]])),data))));cases.push({code:item.code,runner});}
}
const gr=Q.analyze('a+b*c'),gi=cases.length,gitem=S.queries(gr,gr.choices[0].id,'grid');cases.push({code:gitem.code,runner:'for(const auto& row:test'+gi+'::solve({2,3,4})) {for(auto x:row.coordinates)std::cout<<x<<" ";std::cout<<row.value<<"\\n";} try {test'+gi+'::solve({1000,1000,1000});return 23;}catch(const std::exception&){}'});for(let a=0;a<=2;a++)for(let b=0;b<=3;b++)for(let c=0;c<=4;c++)expected.push([a,b,c,a+b*c].join(' '));
let code='#include <bits/stdc++.h>\n';cases.forEach((t,i)=>{const raw=t.code.replace(/^#include[^\n]*\n/gm,'').replace(/(?<![A-Za-z_0-9])::Query/g,'::test'+i+'::Query');code+='namespace test'+i+' {\n'+raw+'\n}\n';assert.deepEqual(S.tokens(S.format(t.code)),S.tokens(t.code));});code+='int main(){'+cases.map(t=>t.runner).join('\n')+'}\n';fs.writeFileSync(path.join(dir,'all.cpp'),code);cp.execFileSync(process.env.CXX||'g++',['-std=c++17','-O2',path.join(dir,'all.cpp'),'-o',path.join(dir,'all.exe')],{timeout:120000,stdio:'pipe'});assert.deepEqual(cp.execFileSync(path.join(dir,'all.exe'),[],{encoding:'utf8',timeout:120000}).trim().split(/\r?\n/),expected);checks+=expected.length;
function standalone(item,input,want,name,extra=[]){fs.writeFileSync(path.join(dir,name+'.cpp'),item.code);cp.execFileSync(process.env.CXX||'g++',['-std=c++17','-O2',...extra,path.join(dir,name+'.cpp'),'-o',path.join(dir,name+'.exe')],{timeout:120000,stdio:'pipe'});assert.equal(cp.execFileSync(path.join(dir,name+'.exe'),[],{input,encoding:'utf8',timeout:120000}).trim().replace(/\r\n/g,'\n'),want);checks++;}
standalone(S.sequence(E.analyze('n^2'),'fast-nth',true),'5\n','25','nth');
standalone(S.sequence(E.analyze('n^2'),'fast-prefix',true),'3\n','0 0\n1 1\n2 4\n3 9','prefix');
const ar=Q.analyze('prod(array(k),k,n,m)');standalone(S.queries(ar,ar.choices[0].id,'queries',true),'4\n2 0 3 4\n3\n0 3\n2 3\n0 0\n','0\n12\n2','array');
standalone(S.queries(gr,gr.choices[0].id,'grid',true),'1 1 1\n','0 0 0 0\n0 0 1 0\n0 1 0 0\n0 1 1 1\n1 0 0 1\n1 0 1 1\n1 1 0 1\n1 1 1 2','grid');
if(process.env.BOOST_INCLUDE){for(const mode of ['direct','recurrence'])standalone(S.sequence(E.analyze('harmonic(n)'),mode,true),'5\n','137/60','exact-'+mode,['-I'+process.env.BOOST_INCLUDE]);}
console.log('PASS solve API / formatted C++ / query order / negative inputs / empty batch / grid / optional main:',checks,'checks,',cases.length,'combined plans. Exact Boost:',!!process.env.BOOST_INCLUDE);console.log('Artifacts:',dir);
